"""Guard the one-source HRP/2 schema and authenticated fixture."""

from __future__ import annotations

import hashlib
import json
from copy import deepcopy
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator
from jsonschema.exceptions import ValidationError
from hermes_relay.v2.protocol import SecureMessage


ROOT = Path(__file__).resolve().parents[1]
PROTOCOL = ROOT / "protocol" / "hrp2"


def _load(name: str) -> dict:
    return json.loads((PROTOCOL / name).read_text(encoding="utf-8"))


def _validator(definition: str) -> Draft202012Validator:
    schema = _load("schema.json")
    return Draft202012Validator({
        "$schema": schema["$schema"],
        "$defs": schema["$defs"],
        "$ref": f"#/$defs/{definition}",
    })


def test_shared_schema_is_valid_draft_2020_12() -> None:
    Draft202012Validator.check_schema(_load("schema.json"))


def test_every_schema_integer_ceiling_is_exact_in_double_backed_json() -> None:
    maximum_safe_integer = (1 << 53) - 1
    schema = _load("schema.json")
    assert schema["$defs"]["uint64"]["maximum"] == maximum_safe_integer

    def maxima(value):
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "maximum" and isinstance(child, int):
                    yield child
                yield from maxima(child)
        elif isinstance(value, list):
            for child in value:
                yield from maxima(child)

    assert all(value <= maximum_safe_integer for value in maxima(schema))


def test_frozen_authenticated_fixture_matches_shared_schema_and_hash() -> None:
    fixture = _load("fixtures/auth-envelope.json")
    _validator("outerEnvelope").validate(fixture["outer_envelope"])
    _validator("secureMessage").validate(fixture["inner_message"])
    encoded = json.dumps(
        fixture["outer_envelope"],
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    assert (
        hashlib.sha256(encoded).hexdigest() == fixture["canonical_envelope_sha256_hex"]
    )


def test_frozen_notification_fixture_matches_shared_schema_and_hash() -> None:
    fixture = _load("fixtures/notification-preview.json")
    _validator("notificationPreview").validate(fixture["preview"])
    _validator("notificationSendDescriptor").validate(fixture["descriptor"])
    encoded = json.dumps(
        fixture["descriptor"],
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    assert (
        hashlib.sha256(encoded).hexdigest()
        == fixture["canonical_descriptor_sha256_hex"]
    )


def test_python_consumes_fixture_emitted_by_production_swift_wire_types() -> None:
    """Consume bytes generated by RelayV2SecureMessage.canonicalJSON().

    The macOS iOS workflow compiles
    ``tests/fixtures/hrp2/SwiftProducedFixture.swift`` together with the
    production JSONValue.swift and RelayV2Protocol.swift, then byte-compares
    its output with this fixture. Linux CI consumes those checked-in bytes
    without pretending to run Apple frameworks or the iOS app.
    """

    fixture_dir = ROOT / "tests" / "fixtures" / "hrp2"
    wire = (fixture_dir / "swift-produced-secure-message.json").read_bytes().strip()
    decoded = json.loads(wire)
    _validator("secureMessage").validate(decoded)

    message = SecureMessage.from_bytes(wire)
    assert message.kind.value == "stream_ack"
    assert message.sender_key_generation == 7
    assert message.body == {
        "stream_id": "str_swift_produced",
        "through_seq": 17,
    }
    # Python's canonical encoder reproduces the exact bytes emitted by the
    # production Swift canonical encoder, including whole-number JSON syntax.
    assert message.to_bytes() == wire


def test_outer_schema_has_no_plaintext_application_fields() -> None:
    properties = _load("schema.json")["$defs"]["outerEnvelope"]["properties"]
    assert (
        not {
            "session_id",
            "turn_id",
            "item_id",
            "method",
            "prompt",
            "title",
            "body",
            "request_id",
        }
        & properties.keys()
    )


def test_pairing_and_inner_wire_objects_reject_unknown_fields() -> None:
    offer = {
        "v": 2,
        "hub": "https://relay.example",
        "relay_route": "rte_agent",
        "offer_route": "off_mailbox",
        "offer_id": "ofr_fixture",
        "offer_transport_token": "d" * 43,
        "expires_at_ms": 1784450000000,
        "relay_kem_pub": "e" * 43,
        "relay_sign_pub": "f" * 43,
        "pair_secret": "g" * 43,
    }
    _validator("pairingOffer").validate(offer)
    with pytest.raises(ValidationError):
        _validator("pairingOffer").validate({**offer, "gateway_token": "forbidden"})

    pair_init = {
        "v": 2,
        "offer_id": "ofr_fixture",
        "device_name": "Fixture iPhone",
        "device_kem_pub": "a" * 43,
        "device_sign_pub": "b" * 43,
        "preview_kem_pub": "c" * 43,
        "device_nonce": "n" * 22,
        "push_bind_token": None,
        "hub_activation_token": None,
        "pair_mac": "m" * 43,
    }
    _validator("pairInit").validate(pair_init)
    with pytest.raises(ValidationError):
        _validator("pairInit").validate({**pair_init, "push_bind_token": ""})

    stream_ack = {
        "v": 2,
        "mid": "ABEiM0RVZneImaq7zN3u_w",
        "kind": "stream_ack",
        "sender_key_generation": 1,
        "created_at_ms": 1784449900000,
        "expires_at_ms": 1784450000000,
        "body": {"stream_id": "str_fixture", "through_seq": 7},
    }
    _validator("secureMessage").validate(stream_ack)
    malformed = deepcopy(stream_ack)
    malformed["body"]["session_id"] = "not_allowed"
    with pytest.raises(ValidationError):
        _validator("secureMessage").validate(malformed)


def test_rpc_and_approval_action_shapes_are_exact() -> None:
    request = {
        "jsonrpc": "2.0",
        "id": "rpc_fixture",
        "method": "prompt.submit",
        "params": {
            "text": "hello",
            "client_message_id": "018f47a0-63f2-7c64-8f16-b78e42c35db9",
        },
        "op_id": "op_fixture",
    }
    _validator("rpcRequest").validate(request)
    without_op = dict(request)
    without_op.pop("op_id")
    with pytest.raises(ValidationError):
        _validator("rpcRequest").validate(without_op)
    malformed_id = deepcopy(request)
    malformed_id["params"]["client_message_id"] = "msg_fixture_123456"
    with pytest.raises(ValidationError):
        _validator("rpcRequest").validate(malformed_id)
    unknown_param = deepcopy(request)
    unknown_param["params"]["gateway_token"] = "forbidden"
    with pytest.raises(ValidationError):
        _validator("rpcRequest").validate(unknown_param)

    boundary = deepcopy(request)
    boundary["id"] = "r" * 128
    boundary["op_id"] = "o" * 128
    boundary["params"]["session_id"] = "s" * 256
    _validator("rpcRequest").validate(boundary)
    for path, invalid in (
        (("id",), "r" * 129),
        (("op_id",), "short"),
        (("params", "session_id"), "s" * 257),
    ):
        malformed = deepcopy(boundary)
        target = malformed
        for component in path[:-1]:
            target = target[component]
        target[path[-1]] = invalid
        with pytest.raises(ValidationError):
            _validator("rpcRequest").validate(malformed)

    action = _load("fixtures/notification-preview.json")["preview"]["action"]
    _validator("approvalAction").validate(action)
    with pytest.raises(ValidationError):
        _validator("approvalAction").validate({
            **action,
            "gateway_url": "https://forbidden",
        })


def test_stream_integer_boundaries_match_exact_cross_runtime_json() -> None:
    batch = {
        "stream_id": "str_fixture",
        "first_seq": 1,
        "frames": [
            {
                "sid": "session_fixture",
                "turn": "turn_fixture",
                "kind": "turn.started",
                "body": {},
            }
        ],
    }
    _validator("frameBatch").validate(batch)
    _validator("frameBatch").validate({**batch, "first_seq": (1 << 53) - 1})
    for invalid in (0, 1 << 53):
        with pytest.raises(ValidationError):
            _validator("frameBatch").validate({**batch, "first_seq": invalid})

    checkpoint = {
        "stream_id": "str_fixture",
        "through_seq": 0,
        "session_id": "session_fixture",
        "snapshot_revision": 0,
        "replace": True,
        "items": [],
        "tombstones": [],
    }
    _validator("checkpoint").validate(checkpoint)
    with pytest.raises(ValidationError):
        _validator("checkpoint").validate({**checkpoint, "through_seq": 1 << 53})
