#!/usr/bin/env bash
# install-loop-digest.sh — schedule the READ-ONLY loop digest as a LOCAL launchd job.
#
# WHY LOCAL (not a cloud Routine): the digest reads machine-local `~/bin/cc-usage`
# and this worktree's governor.json — a cloud container can't see either (the same
# reason asc-poll's cloud-cron idea was dropped). So it runs on THIS Mac, like the
# other ai.hermes.* jobs.
#
# It is READ-ONLY (Linear GraphQL queries + cc-usage + governor.json); it mutates
# nothing, so it is safe to run unattended on a schedule.
#
#   scripts/install-loop-digest.sh install [HH]   # daily at HH:00 local (default 09)
#   scripts/install-loop-digest.sh run            # run once now, print to the log
#   scripts/install-loop-digest.sh uninstall      # remove the launchd job
#   scripts/install-loop-digest.sh logs           # tail the digest log
#
# PREREQUISITE (yours — a credential, so not auto-created): put your Linear personal
# API key in  .hermes-dev/secrets/linear.key  (chmod 0600).  Without it the digest
# still runs and prints the governor + budget sections, just skips the Linear board.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABEL="ai.hermes.loop-digest"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
KEY_FILE="$REPO_ROOT/.hermes-dev/secrets/linear.key"   # gitignored (under .hermes-dev)
WRAP="$REPO_ROOT/.hermes-dev/bin/loop-digest-service"
LOG="$REPO_ROOT/.hermes-dev/logs/loop-digest.log"
NODE="$(command -v node || echo /opt/homebrew/bin/node)"
HOUR="${2:-09}"

say(){ printf '[loop-digest] %s\n' "$*" >&2; }

write_wrapper(){
  mkdir -p "$(dirname "$WRAP")" "$(dirname "$LOG")"
  cat > "$WRAP" <<WRAP_EOF
#!/bin/zsh
# Generated by scripts/install-loop-digest.sh — read-only digest runner.
set -uo pipefail
# Load the Linear key from the gitignored key file if present (never inline in the plist).
[ -f "$KEY_FILE" ] && export LINEAR_API_KEY="\$(head -n1 "$KEY_FILE" | tr -d '[:space:]')"
export PATH="/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
echo "===== \$(date '+%Y-%m-%d %H:%M:%S') ====="
exec "$NODE" "$REPO_ROOT/scripts/loop-digest.mjs"
WRAP_EOF
  chmod +x "$WRAP"
}

case "${1:-}" in
  install)
    [ -x "$NODE" ] || { say "node not found; set PATH or install node"; exit 1; }
    write_wrapper
    cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>              <string>$LABEL</string>
  <key>ProgramArguments</key>   <array><string>$WRAP</string></array>
  <key>StartCalendarInterval</key><dict><key>Hour</key><integer>$HOUR</integer><key>Minute</key><integer>0</integer></dict>
  <key>StandardOutPath</key>    <string>$LOG</string>
  <key>StandardErrorPath</key>  <string>$LOG</string>
  <key>RunAtLoad</key>          <false/>
  <key>LimitLoadToSessionType</key><string>Aqua</string>
</dict>
</plist>
PLIST_EOF
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load "$PLIST"
    say "installed $LABEL — daily at ${HOUR}:00 local. Log: $LOG"
    [ -f "$KEY_FILE" ] && say "Linear key present (full board)." || say "NOTE: no $KEY_FILE — board section will be skipped until you add your Linear key there (chmod 600)."
    ;;
  run)        write_wrapper; "$WRAP"; ;;
  uninstall)  launchctl unload "$PLIST" 2>/dev/null || true; rm -f "$PLIST"; say "removed $LABEL (wrapper/log kept)"; ;;
  logs)       tail -n 60 -f "$LOG"; ;;
  *) echo "usage: $0 {install [HH]|run|uninstall|logs}" >&2; exit 2 ;;
esac
